# Generated by Django 6.0.7 on 2026-08-04 03:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'Leetcode'), ('codechef', 'Codechef'), ('atcoder', 'Atcoder')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'Leetcode'), ('codechef', 'Codechef'), ('atcoder', 'Atcoder')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['starts_at'], name='core_contes_starts__1ac797_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='contest_ends_after_start')],
            },
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'Leetcode'), ('codechef', 'Codechef'), ('atcoder', 'Atcoder')], max_length=20)),
                ('handle', models.CharField(max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('solved', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('place', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_points', to='core.platformaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SavedContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_minutes_before', models.PositiveIntegerField(default=30)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_contests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('verdict', models.CharField(choices=[('AC', 'Ac'), ('WA', 'Wa'), ('TLE', 'Tle'), ('MLE', 'Mle'), ('RE', 'Re'), ('CE', 'Ce')], max_length=10)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.platformaccount')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='core.tag'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'friend'), name='uniq_friendship'), models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='no_self_friendship')],
            },
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='uniq_account_per_platform'),
        ),
        migrations.AddIndex(
            model_name='ratingpoint',
            index=models.Index(fields=['account', 'occurred_at'], name='core_rating_account_3ab218_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratingpoint',
            constraint=models.UniqueConstraint(fields=('account', 'occurred_at'), name='uniq_rating_point'),
        ),
        migrations.AddConstraint(
            model_name='savedcontest',
            constraint=models.UniqueConstraint(fields=('user', 'contest'), name='uniq_saved_contest'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['account', '-submitted_at'], name='core_submis_account_fa9626_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['account', 'problem', 'verdict'], name='core_submis_account_a3ec19_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('account', 'external_id'), name='uniq_submission_per_account'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['platform', 'rating'], name='core_proble_platfor_a8eac5_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('platform', 'external_id'), name='uniq_problem_per_platform'),
        ),
    ]
